spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/magictickets_db
    username: magic_user
    password: magic_password
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false